### PR TITLE
Organized ForgeHooks

### PR DESCRIPTION
**Pull request by obj-obj**

### CODE REVIEW

**Comment by obj-obj** [comment]
Why does it show my old username on the commits...

**Comment by kitlith** [comment]
Your local git configuration might have the wrong name/email setup, as that's what github uses to detech what commits came from who.

**Comment by obj-obj** [comment]
Ah, it did still have my old user
fixed that

**Comment by obj-obj** [comment]
oops

**Comment by obj-obj** [comment]
This isn't going to be approved so im just gonna close it
Doesn't really have a point anyway

**Pull request closed without merging**
